# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16a6303e197dd12720dd590600b9bf9ed83f822e87ccade1fbf7476f0e2ec87cb002e1c94dde02f71f0d1391a47ed04d871d37370f1effac5008f5d2d51b9d98

test:
  secret_key_base: 2550bbc46ebe6c8cf3e71fbdde46adf5e7ac8335cb1286c765f280abb9a0a630c5d5f358498d7026fe24ff42ea67cb63c2a1f9b3c634da3e21620b77ca39bb12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
